-- DROP TABLE items;

CREATE TABLE items
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    amount integer NOT NULL,
    price character varying(50) NOT NULL,
    title character varying(50) NOT NULL,
    CONSTRAINT items_pkey PRIMARY KEY (id)
)