-- DROP TABLE Users;

CREATE TABLE Users
(
    id integer NOT NULL GENERATED BY DEFAULT AS IDENTITY,
    login character varying(50) NOT NULL,
    password character varying(50) NOT NULL,
    CONSTRAINT Users_pkey PRIMARY KEY (id)
)